# Generated by Django 4.2.1 on 2023-07-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_dislike_count_post_likes_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes_count',
            new_name='like_count',
        ),
    ]
