# Generated by Django 4.2.1 on 2023-07-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_dislike_count_remove_post_like_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_choice',
        ),
    ]
