# Generated by Django 4.2.1 on 2023-06-20 14:49

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='default bio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default='USA', max_length=255),
            preserve_default=False,
        ),
    ]
